[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6 --always-print-stacktrace --no-location --catch-hardfault"


[unstable]
build-std = ["core"]

[env]
ESP_LOG="INFO"